language: node_js
node_js:
      - "node"
services:
      - postgresql

cache:
  directories:
    - "node_modules"

env:
  global:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=
    - POSTGRES_DB=russia
    - DB_HOST=127.0.0.1
    - JWT_SECRET=random_secret

# Add database
before_install:
  - psql -c 'CREATE DATABASE russia;' -U postgres

# Install dependencies
install:
  - npm install

# Run build
before_script:
  - npm run build

# Run tests
script:
  - NODE_ENV=production npm test
