version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=postgresql
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - JWT_SECRET
      - FIREBASE_PROJECT_ID
      - FIREBASE_CLIENT_EMAIL
      - FIREBASE_PRIVATE_KEY
      - FIREBASE_DATABASE_URL
      - DIRECTIONS_API_KEY
    volumes:
      - ${DATA_PATH}/uploads:/usr/src/app/uploads
    links:
      - postgresql
    depends_on:
      - postgresql
    restart: always
  postgresql:
    image: "postgres:10-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - ${DATA_PATH}/pg:/var/lib/postgresql/data
    restart: always
