version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - JWT_SECRET
      - DB_HOST=postgresql
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - FIREBASE_PRIVATE_KEY
      - DIRECTIONS_API_KEY
    links:
      - postgresql
    depends_on:
      - postgresql
    restart: always
  postgresql:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - ${DATA_PATH}/pg:/var/lib/postgresql/data
    restart: always
